### ISSUE TITLE
[1.0.3] Milla's Charged Shield Burst is inconsistent

### ISSUE THREAD

**Issue by MrNaxeros** [GalaxyTrail/fp2bugs#76]
Milla's shield burst seems to have shorter range than the visuals show.
The issue is especialy visible on those slashing tentacles.

https://youtu.be/Dn_ZVJ6V00Q

**Comment by SpaceyStrife** [comment]
After scratching my head over this for months, I've finally figured out the cause. The way collision checks work is that the game checks if Object A's hitbox is inside of Object B's hitbox. The reason for Milla's shield burst whiffing so much is because I plugged it in as Object A, but because it's such a huge hitbox that's often bigger than the enemy it's trying to hit, the game get confused about when it's "inside" the enemy hitbox. Swapping it around to Object B fixed it.
